import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import { readFileSync, copyFileSync } from 'fs';
import yaml from 'js-yaml';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

// Plugin to load YAML files
const yamlPlugin = {
  name: 'yaml',
  setup(build) {
    build.onLoad({ filter: /\.yaml$/ }, async (args) => {
      const yamlContent = readFileSync(args.path, 'utf8');
      const parsed = yaml.load(yamlContent);
      return {
        contents: `export default ${JSON.stringify(parsed)}`,
        loader: 'js',
      };
    });
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  plugins: [yamlPlugin],
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins,
  ],
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'dist/main.js',
  minify: prod,
});

// Function to copy static files to dist
function copyStaticFiles() {
  console.log('Copying static files to dist...');
  copyFileSync('src/manifest.json', 'dist/manifest.json');
  copyFileSync('src/styles.css', 'dist/styles.css');
  console.log('  ✓ Copied manifest.json');
  console.log('  ✓ Copied styles.css');
}

if (prod) {
  await context.rebuild();
  copyStaticFiles();
  process.exit(0);
} else {
  await context.rebuild();
  copyStaticFiles();
  await context.watch();
}
