import { BibleBook } from '@/types';

export const bibleBooksEN: readonly BibleBook[] = [
  {
    id: 1,
    aliases: ['genesis'],
    longName: 'Genesis',
    shortName: 'Ge',
  },
  {
    id: 2,
    aliases: ['exodus'],
    longName: 'Exodus',
    shortName: 'Ex',
  },
  {
    id: 3,
    aliases: ['leviticus'],
    longName: 'Leviticus',
    shortName: 'Le',
  },
  {
    id: 4,
    aliases: ['numbers'],
    longName: 'Numbers',
    shortName: 'Nu',
  },
  {
    id: 5,
    aliases: ['deuteronomy'],
    longName: 'Deuteronomy',
    shortName: 'De',
  },
  {
    id: 6,
    aliases: ['joshua'],
    longName: 'Joshua',
    shortName: 'Jos',
  },
  {
    id: 7,
    aliases: ['judges', 'jg'],
    longName: 'Judges',
    shortName: 'Jg',
  },
  {
    id: 8,
    aliases: ['ruth'],
    longName: 'Ruth',
    shortName: 'Ru',
  },
  {
    id: 9,
    prefix: '1',
    aliases: ['samuel'],
    longName: '1 Samuel',
    shortName: '1Sa',
  },
  {
    id: 10,
    prefix: '2',
    aliases: ['samuel'],
    longName: '2 Samuel',
    shortName: '2Sa',
  },
  {
    id: 11,
    prefix: '1',
    aliases: ['kings'],
    longName: '1 Kings',
    shortName: '1Ki',
  },
  {
    id: 12,
    prefix: '2',
    aliases: ['kings'],
    longName: '2 Kings',
    shortName: '2Ki',
  },
  {
    id: 13,
    prefix: '1',
    aliases: ['chronicles'],
    longName: '1 Chronicles',
    shortName: '1Ch',
  },
  {
    id: 14,
    prefix: '2',
    aliases: ['chronicles'],
    longName: '2 Chronicles',
    shortName: '2Ch',
  },
  {
    id: 15,
    aliases: ['ezra'],
    longName: 'Ezra',
    shortName: 'Ezr',
  },
  {
    id: 16,
    aliases: ['nehemiah'],
    longName: 'Nehemiah',
    shortName: 'Ne',
  },
  {
    id: 17,
    aliases: ['esther'],
    longName: 'Esther',
    shortName: 'Es',
  },
  {
    id: 18,
    aliases: ['job'],
    longName: 'Job',
    shortName: 'Job',
  },
  {
    id: 19,
    aliases: ['psalms'],
    longName: 'Psalms',
    shortName: 'Ps',
  },
  {
    id: 20,
    aliases: ['proverbs'],
    longName: 'Proverbs',
    shortName: 'Pr',
  },
  {
    id: 21,
    aliases: ['ecclesiastes'],
    longName: 'Ecclesiastes',
    shortName: 'Ec',
  },
  {
    id: 22,
    aliases: ['can', 'songofsolomon', 'songofsongs'],
    longName: 'Song of Solomon',
    shortName: 'Ca',
  },
  {
    id: 23,
    aliases: ['isaiah'],
    longName: 'Isaiah',
    shortName: 'Isa',
  },
  {
    id: 24,
    aliases: ['jeremiah'],
    longName: 'Jeremiah',
    shortName: 'Jer',
  },
  {
    id: 25,
    aliases: ['lamentations'],
    longName: 'Lamentations',
    shortName: 'La',
  },
  {
    id: 26,
    aliases: ['ezekiel'],
    longName: 'Ezekiel',
    shortName: 'Eze',
  },
  {
    id: 27,
    aliases: ['daniel'],
    longName: 'Daniel',
    shortName: 'Da',
  },
  {
    id: 28,
    aliases: ['hosea'],
    longName: 'Hosea',
    shortName: 'Ho',
  },
  {
    id: 29,
    aliases: ['joel'],
    longName: 'Joel',
    shortName: 'Joe',
  },
  {
    id: 30,
    aliases: ['amos'],
    longName: 'Amos',
    shortName: 'Am',
  },
  {
    id: 31,
    aliases: ['obadiah'],
    longName: 'Obadiah',
    shortName: 'Ob',
  },
  {
    id: 32,
    aliases: ['jonah', 'jnh'],
    longName: 'Jonah',
    shortName: 'Jon',
  },
  {
    id: 33,
    aliases: ['micah'],
    longName: 'Micah',
    shortName: 'Mic',
  },
  {
    id: 34,
    aliases: ['nahum'],
    longName: 'Nahum',
    shortName: 'Na',
  },
  {
    id: 35,
    aliases: ['habakkuk'],
    longName: 'Habakkuk',
    shortName: 'Hab',
  },
  {
    id: 36,
    aliases: ['zephaniah'],
    longName: 'Zephaniah',
    shortName: 'Zep',
  },
  {
    id: 37,
    aliases: ['haggai'],
    longName: 'Haggai',
    shortName: 'Hag',
  },
  {
    id: 38,
    aliases: ['zechariah'],
    longName: 'Zechariah',
    shortName: 'Zec',
  },
  {
    id: 39,
    aliases: ['malachi'],
    longName: 'Malachi',
    shortName: 'Mal',
  },
  {
    id: 40,
    aliases: ['matthew', 'mt'],
    longName: 'Matthew',
    shortName: 'Mt',
  },
  {
    id: 41,
    aliases: ['mark', 'mr'],
    longName: 'Mark',
    shortName: 'Mr',
  },
  {
    id: 42,
    aliases: ['luke'],
    longName: 'Luke',
    shortName: 'Lu',
  },
  {
    id: 43,
    aliases: ['john'],
    longName: 'John',
    shortName: 'Joh',
  },
  {
    id: 44,
    aliases: ['acts'],
    longName: 'Acts',
    shortName: 'Ac',
  },
  {
    id: 45,
    aliases: ['romans'],
    longName: 'Romans',
    shortName: 'Ro',
  },
  {
    id: 46,
    prefix: '1',
    aliases: ['corinthians'],
    longName: '1 Corinthians',
    shortName: '1Co',
  },
  {
    id: 47,
    prefix: '2',
    aliases: ['corinthians'],
    longName: '2 Corinthians',
    shortName: '2Co',
  },
  {
    id: 48,
    aliases: ['galatians'],
    longName: 'Galatians',
    shortName: 'Ga',
  },
  {
    id: 49,
    aliases: ['ephesians'],
    longName: 'Ephesians',
    shortName: 'Eph',
  },
  {
    id: 50,
    aliases: ['philippians', 'php'],
    longName: 'Philippians',
    shortName: 'Php',
  },
  {
    id: 51,
    aliases: ['colossians'],
    longName: 'Colossians',
    shortName: 'Col',
  },
  {
    id: 52,
    prefix: '1',
    aliases: ['thessalonians'],
    longName: '1 Thessalonians',
    shortName: '1Th',
  },
  {
    id: 53,
    prefix: '2',
    aliases: ['thessalonians'],
    longName: '2 Thessalonians',
    shortName: '2Th',
  },
  {
    id: 54,
    prefix: '1',
    aliases: ['timothy'],
    longName: '1 Timothy',
    shortName: '1Ti',
  },
  {
    id: 55,
    prefix: '2',
    aliases: ['timothy'],
    longName: '2 Timothy',
    shortName: '2Ti',
  },
  {
    id: 56,
    aliases: ['titus'],
    longName: 'Titus',
    shortName: 'Tit',
  },
  {
    id: 57,
    aliases: ['philemon', 'phm'],
    longName: 'Philemon',
    shortName: 'Phm',
  },
  {
    id: 58,
    aliases: ['hebrews'],
    longName: 'Hebrews',
    shortName: 'Heb',
  },
  {
    id: 59,
    aliases: ['james', 'jas'],
    longName: 'James',
    shortName: 'Jas',
  },
  {
    id: 60,
    prefix: '1',
    aliases: ['peter'],
    longName: '1 Peter',
    shortName: '1Pe',
  },
  {
    id: 61,
    prefix: '2',
    aliases: ['peter'],
    longName: '2 Peter',
    shortName: '2Pe',
  },
  {
    id: 62,
    prefix: '1',
    aliases: ['john'],
    longName: '1 John',
    shortName: '1Jo',
  },
  {
    id: 63,
    prefix: '2',
    aliases: ['john'],
    longName: '2 John',
    shortName: '2Jo',
  },
  {
    id: 64,
    prefix: '3',
    aliases: ['john'],
    longName: '3 John',
    shortName: '3Jo',
  },
  {
    id: 65,
    aliases: ['jude'],
    longName: 'Jude',
    shortName: 'Jude',
  },
  {
    id: 66,
    aliases: ['revelation'],
    longName: 'Revelation',
    shortName: 'Re',
  },
];
