import { BibleBook } from '@/types';

export const bibleBooksEN: readonly BibleBook[] = [
  {
    id: 1,
    aliases: ['gen', 'ge', 'genesis'],
    longName: 'Genesis',
    shortName: 'Ge',
  },
  {
    id: 2,
    aliases: ['ex', 'exo', 'exodus'],
    longName: 'Exodus',
    shortName: 'Ex',
  },
  {
    id: 3,
    aliases: ['lev', 'le', 'leviticus'],
    longName: 'Leviticus',
    shortName: 'Le',
  },
  {
    id: 4,
    aliases: ['num', 'nu', 'numbers'],
    longName: 'Numbers',
    shortName: 'Nu',
  },
  {
    id: 5,
    aliases: ['deut', 'de', 'deuteronomy'],
    longName: 'Deuteronomy',
    shortName: 'De',
  },
  {
    id: 6,
    aliases: ['jos', 'joshua'],
    longName: 'Joshua',
    shortName: 'Jos',
  },
  {
    id: 7,
    aliases: ['jg', 'judg', 'judges'],
    longName: 'Judges',
    shortName: 'Jg',
  },
  {
    id: 8,
    aliases: ['ru', 'rut', 'ruth'],
    longName: 'Ruth',
    shortName: 'Ru',
  },
  {
    id: 9,
    aliases: ['1sa', '1sam', '1samuel', '1.samuel'],
    longName: '1 Samuel',
    shortName: '1Sa',
  },
  {
    id: 10,
    aliases: ['2sa', '2sam', '2samuel', '2.samuel'],
    longName: '2 Samuel',
    shortName: '2Sa',
  },
  {
    id: 11,
    aliases: ['1ki', '1king', '1kings', '1.kings'],
    longName: '1 Kings',
    shortName: '1Ki',
  },
  {
    id: 12,
    aliases: ['2ki', '2king', '2kings', '2.kings'],
    longName: '2 Kings',
    shortName: '2Ki',
  },
  {
    id: 13,
    aliases: ['1ch', '1chr', '1chron', '1chronicles'],
    longName: '1 Chronicles',
    shortName: '1Ch',
  },
  {
    id: 14,
    aliases: ['2ch', '2chr', '2chron', '2chronicles'],
    longName: '2 Chronicles',
    shortName: '2Ch',
  },
  {
    id: 15,
    aliases: ['ezr', 'ezra'],
    longName: 'Ezra',
    shortName: 'Ezr',
  },
  {
    id: 16,
    aliases: ['ne', 'neh', 'nehemiah'],
    longName: 'Nehemiah',
    shortName: 'Ne',
  },
  {
    id: 17,
    aliases: ['es', 'est', 'esther'],
    longName: 'Esther',
    shortName: 'Es',
  },
  {
    id: 18,
    aliases: ['job'],
    longName: 'Job',
    shortName: 'Job',
  },
  {
    id: 19,
    aliases: ['ps', 'psa', 'psalm', 'psalms'],
    longName: 'Psalms',
    shortName: 'Ps',
  },
  {
    id: 20,
    aliases: ['pr', 'pro', 'prov', 'proverbs'],
    longName: 'Proverbs',
    shortName: 'Pr',
  },
  {
    id: 21,
    aliases: ['ec', 'ecc', 'eccl', 'ecclesiastes'],
    longName: 'Ecclesiastes',
    shortName: 'Ec',
  },
  {
    id: 22,
    aliases: ['ca', 'can', 'song', 'songofsolomon', 'songofsongs'],
    longName: 'Song of Solomon',
    shortName: 'Ca',
  },
  {
    id: 23,
    aliases: ['isa', 'is', 'isaiah'],
    longName: 'Isaiah',
    shortName: 'Isa',
  },
  {
    id: 24,
    aliases: ['jer', 'jeremiah'],
    longName: 'Jeremiah',
    shortName: 'Jer',
  },
  {
    id: 25,
    aliases: ['la', 'lam', 'lamentations'],
    longName: 'Lamentations',
    shortName: 'La',
  },
  {
    id: 26,
    aliases: ['eze', 'ezek', 'ezekiel'],
    longName: 'Ezekiel',
    shortName: 'Eze',
  },
  {
    id: 27,
    aliases: ['da', 'dan', 'daniel'],
    longName: 'Daniel',
    shortName: 'Da',
  },
  {
    id: 28,
    aliases: ['ho', 'hos', 'hosea'],
    longName: 'Hosea',
    shortName: 'Ho',
  },
  {
    id: 29,
    aliases: ['joe', 'joel'],
    longName: 'Joel',
    shortName: 'Joe',
  },
  {
    id: 30,
    aliases: ['am', 'amos'],
    longName: 'Amos',
    shortName: 'Am',
  },
  {
    id: 31,
    aliases: ['ob', 'oba', 'obadiah'],
    longName: 'Obadiah',
    shortName: 'Ob',
  },
  {
    id: 32,
    aliases: ['jon', 'jnh', 'jonah'],
    longName: 'Jonah',
    shortName: 'Jon',
  },
  {
    id: 33,
    aliases: ['mic', 'micah'],
    longName: 'Micah',
    shortName: 'Mic',
  },
  {
    id: 34,
    aliases: ['na', 'nah', 'nahum'],
    longName: 'Nahum',
    shortName: 'Na',
  },
  {
    id: 35,
    aliases: ['hab', 'habakkuk'],
    longName: 'Habakkuk',
    shortName: 'Hab',
  },
  {
    id: 36,
    aliases: ['zep', 'zeph', 'zephaniah'],
    longName: 'Zephaniah',
    shortName: 'Zep',
  },
  {
    id: 37,
    aliases: ['hag', 'haggai'],
    longName: 'Haggai',
    shortName: 'Hag',
  },
  {
    id: 38,
    aliases: ['zec', 'zech', 'zechariah'],
    longName: 'Zechariah',
    shortName: 'Zec',
  },
  {
    id: 39,
    aliases: ['mal', 'malachi'],
    longName: 'Malachi',
    shortName: 'Mal',
  },
  {
    id: 40,
    aliases: ['mt', 'mat', 'matt', 'matthew'],
    longName: 'Matthew',
    shortName: 'Mt',
  },
  {
    id: 41,
    aliases: ['mr', 'mark'],
    longName: 'Mark',
    shortName: 'Mr',
  },
  {
    id: 42,
    aliases: ['lu', 'luk', 'luke'],
    longName: 'Luke',
    shortName: 'Lu',
  },
  {
    id: 43,
    aliases: ['joh', 'john'],
    longName: 'John',
    shortName: 'Joh',
  },
  {
    id: 44,
    aliases: ['ac', 'act', 'acts'],
    longName: 'Acts',
    shortName: 'Ac',
  },
  {
    id: 45,
    aliases: ['ro', 'rom', 'romans'],
    longName: 'Romans',
    shortName: 'Ro',
  },
  {
    id: 46,
    aliases: ['1co', '1cor', '1corinthians'],
    longName: '1 Corinthians',
    shortName: '1Co',
  },
  {
    id: 47,
    aliases: ['2co', '2cor', '2corinthians'],
    longName: '2 Corinthians',
    shortName: '2Co',
  },
  {
    id: 48,
    aliases: ['ga', 'gal', 'galatians'],
    longName: 'Galatians',
    shortName: 'Ga',
  },
  {
    id: 49,
    aliases: ['eph', 'ephesians'],
    longName: 'Ephesians',
    shortName: 'Eph',
  },
  {
    id: 50,
    aliases: ['php', 'phil', 'philippians'],
    longName: 'Philippians',
    shortName: 'Php',
  },
  {
    id: 51,
    aliases: ['col', 'colossians'],
    longName: 'Colossians',
    shortName: 'Col',
  },
  {
    id: 52,
    aliases: ['1th', '1thess', '1thessalonians'],
    longName: '1 Thessalonians',
    shortName: '1Th',
  },
  {
    id: 53,
    aliases: ['2th', '2thess', '2thessalonians'],
    longName: '2 Thessalonians',
    shortName: '2Th',
  },
  {
    id: 54,
    aliases: ['1ti', '1tim', '1timothy'],
    longName: '1 Timothy',
    shortName: '1Ti',
  },
  {
    id: 55,
    aliases: ['2ti', '2tim', '2timothy'],
    longName: '2 Timothy',
    shortName: '2Ti',
  },
  {
    id: 56,
    aliases: ['tit', 'titus'],
    longName: 'Titus',
    shortName: 'Tit',
  },
  {
    id: 57,
    aliases: ['phm', 'phile', 'philemon'],
    longName: 'Philemon',
    shortName: 'Phm',
  },
  {
    id: 58,
    aliases: ['heb', 'hebrews'],
    longName: 'Hebrews',
    shortName: 'Heb',
  },
  {
    id: 59,
    aliases: ['jas', 'james'],
    longName: 'James',
    shortName: 'Jas',
  },
  {
    id: 60,
    aliases: ['1pe', '1pet', '1peter'],
    longName: '1 Peter',
    shortName: '1Pe',
  },
  {
    id: 61,
    aliases: ['2pe', '2pet', '2peter'],
    longName: '2 Peter',
    shortName: '2Pe',
  },
  {
    id: 62,
    aliases: ['1jo', '1joh', '1john'],
    longName: '1 John',
    shortName: '1Jo',
  },
  {
    id: 63,
    aliases: ['2jo', '2joh', '2john'],
    longName: '2 John',
    shortName: '2Jo',
  },
  {
    id: 64,
    aliases: ['3jo', '3joh', '3john'],
    longName: '3 John',
    shortName: '3Jo',
  },
  {
    id: 65,
    aliases: ['jude'],
    longName: 'Jude',
    shortName: 'Jude',
  },
  {
    id: 66,
    aliases: ['re', 'rev', 'revelation'],
    longName: 'Revelation',
    shortName: 'Re',
  },
];
