name: Draft Release PR

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write   # Required for tagging the release
  pull-requests: write  # Required for creating release PRs

jobs:
  draft-release:
    name: Draft Release PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.USER_TOKEN }}

      - name: Install changesets cli
        run: npm i -D @changesets/cli @changesets/changelog-github

      - name: Create changesets PR or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          title: 🚀 Release new version
          version: npm run version
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.USER_TOKEN }}
